# Jekyll settings
title: DTNMA Documentation
email: dtnma-support@jhuapl.edu
description: >
  Extra documentation for the DTNMA
  supporting its specifications, reference implementations,
  data models and modules.
baseurl: "/.github" # the subpath of the site
url: "https://jhuapl-dtnma.github.io/dtnma-ace/"
github_username: JHUAPL-DTNMA

# Build settings
permalink: /:year/:title:output_ext
markdown: kramdown
theme: minima
sass:
  quiet_deps: true
